In [13]:
import torch
from torch.autograd import Variable

In [5]:
a = torch.Tensor([[1,2,3],[5,6,7]])
b = torch.Tensor([[1,2,3],[8,10,12]])

In [6]:
a

tensor([[1., 2., 3.],
        [5., 6., 7.]])

In [7]:
b

tensor([[ 1.,  2.,  3.],
        [ 8., 10., 12.]])

In [8]:
torch.cat([a,b],dim=0)

tensor([[ 1.,  2.,  3.],
        [ 5.,  6.,  7.],
        [ 1.,  2.,  3.],
        [ 8., 10., 12.]])

In [19]:
a =Variable(a, requires_grad=True)

In [21]:
a.data

tensor([[1., 2., 3.],
        [5., 6., 7.]])

In [23]:
a.requires_grad

True

## expand


In [49]:
x = torch.FloatTensor([[1], [2], [3]])

In [25]:
x.size()

torch.Size([3, 1])

In [26]:
x

tensor([[1],
        [2],
        [3]])

In [27]:
# -1表示不扩展当前维度
x.expand(-1,5)

tensor([[1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3]])

In [33]:
x.expand(3,-1)

tensor([[1],
        [2],
        [3]])

In [34]:
x

tensor([[1],
        [2],
        [3]])

In [35]:
x.is_contiguous()

True

In [37]:
x.zero_()

tensor([[0],
        [0],
        [0]])

In [59]:
x

tensor([[ 6.2516e-05],
        [-7.1594e-03],
        [-1.1723e-02]])

In [53]:
x.normal_(0,0.01)

tensor([[ 6.2516e-05],
        [-7.1594e-03],
        [-1.1723e-02]])

## new  
创建一个新的Tensor，该Tensor的type和device都和原有Tensor一致，且无内容。

In [60]:
x

tensor([[ 6.2516e-05],
        [-7.1594e-03],
        [-1.1723e-02]])

In [67]:
x.size()

torch.Size([3, 1])

In [68]:
x.new(x.size()).normal_()

tensor([[ 0.9600],
        [-1.7037],
        [ 0.3709]])

In [69]:
x.new(x.size()).zero_()

tensor([[0.],
        [0.],
        [0.]])

## matmul,mm,bmm  
mm:(m,n)(n,p)->(m,p)  
bmm:(b,m,n)(b,n,p)->(b,m,p)  
matmul:

In [70]:
a = torch.arange(0,18).view(2,3,3)
b = torch.ones(3,dtype=torch.long)

In [71]:
a

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]])

In [72]:
b

tensor([1, 1, 1])

In [74]:
c = torch.matmul(a,b)
d = torch.matmul(b,a)

In [75]:
c

tensor([[ 3, 12, 21],
        [30, 39, 48]])

In [76]:
d

tensor([[ 9, 12, 15],
        [36, 39, 42]])