In [17]:
import numpy as np
import scipy.sparse as sp

In [2]:
a = np.arange(12).reshape(3,4)

In [3]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### flatten()

In [6]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### np.where()  
用法一：conditon,x,y  
用法二：condition    返回非0元素坐标

In [7]:
np.where(a>=2, 2, -2)

array([[-2, -2,  2,  2],
       [ 2,  2,  2,  2],
       [ 2,  2,  2,  2]])

In [8]:
np.where(a)

(array([0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2]),
 array([1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]))

### multiply   dot

multiply  
数组和矩阵对应位置相乘，输出与相乘数组/矩阵的大小一致

In [9]:
A = np.arange(1,5).reshape(2,2)
B = np.arange(0,4).reshape(2,2)

In [11]:
np.multiply(A, B)

array([[ 0,  2],
       [ 6, 12]])

In [12]:
np.mat(A).multiply(np.mat(B))

AttributeError: 'matrix' object has no attribute 'multiply'

dot  
矩阵乘法

In [13]:
A.dot(B)

array([[ 4,  7],
       [ 8, 15]])

In [16]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
sp.eye(4).todense()

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [20]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.power()