In [7]:
import random
import scipy.sparse as sp
import numpy

## 创建稀疏矩阵

### coo_matrix类创建稀疏矩阵   
三元组，ijv

In [26]:
# 随机产生行、列坐标和值
a = random.sample(range(10),5)
b = random.sample(range(10),5)
c = random.sample(range(100),5)
# 将list数据转为array数组
rows = np.array(a)
cols = np.array(b)
v = np.array(c)
# coo_matrix函数生成稀疏矩阵
sparseM = sp.coo_matrix((v,(rows,cols)))
# todense将稀疏矩阵转为完全阵
fullM = sparseM.todense()

In [74]:
sparseM.todense()

matrix([[78,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0, 86,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0, 72,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  4],
        [ 0, 73,  0,  0,  0,  0,  0,  0,  0,  0]])

In [81]:
rowsum = np.array(sparse_csc.sum(1))
np.power(np.multiply(np.eye(3), rowsum), -1)

/Users/jiachangmin/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in power
  


array([[0.2       ,        inf,        inf],
       [       inf, 0.2       ,        inf],
       [       inf,        inf, 0.09090909]])

In [78]:
rowsum

array([[ 5],
       [ 5],
       [11]], dtype=int64)

### csc_matrix类创建稀疏矩阵  
真正的csc_matrix创建稀疏矩阵 csc_matrix类，实际就是数据结构里按列存储稀疏矩阵时，给出每列里非零个数，以及列里那几行是非零值。  
csc_matrix((data, indices, indptr), [shape=(M, N)])

总结一下csc_matrix的各个参数含义，data是稀疏矩阵的值；indices给出各列非0数据所在的行号；  
indptr则是给出前i列非0元素个数：indptr[0]表示第0列前有0个，indptr[1]第1列前共有0列那么  
多个实际是第0列非0个数，indptr[2]在则是记录了0、1列一共有多少个非0元素。

In [59]:
data = np.array([1, 2, 3, 4, 5, 6])
indptr = np.array([0, 2, 3, 6])
indices = np.array([0, 2, 2, 0, 1, 2])
sparse_csc = sp.csc_matrix((data, indices, indptr), shape=(3,3))
print(sparse_csc.todense())
print(sparse_csc.T.todense())

[[1 0 4]
 [0 0 5]
 [2 3 6]]
[[1 0 2]
 [0 0 3]
 [4 5 6]]


In [62]:
(sparse_csc.T > sparse_csc).todense()

matrix([[False, False, False],
        [False, False, False],
        [ True,  True, False]])

In [65]:
sparse_csc.multiply(sparse_csc.T).todense()

matrix([[ 1,  0,  8],
        [ 0,  0, 15],
        [ 8, 15, 36]], dtype=int64)

In [73]:
sparse_csc

<3x3 sparse matrix of type '<class 'numpy.int64'>'
	with 6 stored elements in Compressed Sparse Column format>

In [72]:
rowsum = np.array(sparse_csc.sum(1))
r_inv = np.power(rowsum, -1).flatten()

ValueError: Integers to negative integer powers are not allowed.

In [70]:
rowsum

array([[ 5],
       [ 5],
       [11]], dtype=int64)

自己生成该矩阵  
 [[  0.   0.   0.   0.]  
 [  0.   0.  12.   0.]  
 [  0.   0.  0.   22.]]

In [52]:
data = np.array([12, 22])
indices = np.array([1, 2])
indptr = np.array([0, 0, 0, 1, 2])
sparse_csc_ = sp.csc_matrix((data, indices, indptr), shape=(3,4))
print(sparse_csc_.todense())

[[ 0  0  0  0]
 [ 0  0 12  0]
 [ 0  0  0 22]]


### csr_matrix类创建稀疏矩阵  
csr_matrix类是按行存储矩阵，和csc_matrix按列正好相对应。

In [53]:
data = np.array([12, 22])
indices = np.array([2, 3])
indptr = np.array([0, 0, 1, 2])
sparse_csr = sp.csr_matrix((data, indices, indptr), shape=(3,4))
print(sparse_csr.todense())

[[ 0  0  0  0]
 [ 0  0 12  0]
 [ 0  0  0 22]]


### bsr_matrix类创建稀疏矩阵

In [58]:
data = np.array([12, 22]).repeat(6).reshape(2,2,3)
indices = np.array([2,3])
indptr = np.array([0,0,1,2])
sparse_bsr = sp.bsr_matrix((data, indices, indptr), shape=(6,12))
print(sparse_bsr.todense())

[[ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 12 12 12  0  0  0]
 [ 0  0  0  0  0  0 12 12 12  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 22 22 22]
 [ 0  0  0  0  0  0  0  0  0 22 22 22]]


In [39]:
sparseM.nonzero()

(array([3, 7, 0, 2, 8], dtype=int32), array([8, 9, 0, 4, 1], dtype=int32))

In [42]:
sparseM.shape

(9, 10)